[[plugins]]
# 非同期で外部コマンドを実行したりとか
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
# colorscheme
repo = "tomasr/molokai"

[[plugins]]
# text-object の縁側版
repo = "tpope/vim-surround"

[[plugins]]
# vim-surrond とかの操作をリピートできる
repo = "tpope/vim-repeat"

[[plugins]]
# テキスト整形用
repo = "h1mesuke/vim-alignta"

[[plugins]]
# レジスタの履歴を取得・再利用する<c-p>, <c-n>
repo = "LeafCage/yankround.vim"

[[plugins]]
# カレンダー
repo = "vim-scripts/calendar.vim"

[[plugins]]
# nishigori/increment-activator
repo = "nishigori/increment-activator"

[[plugins]]
# [, (, {, ", ' に対して閉じカッコを補完
repo = "kana/vim-smartinput"

[[plugins]]
# do などに対して end を補完
repo = "cohama/vim-smartinput-endwise"
depends = 'vim-smartinput'

[[plugins]]
# vim の正規表現を Perl や Ruby っぽくする
repo = "othree/eregex.vim"

[[plugins]]
# シンタックスチェックや臭いコードを調べる
repo = "scrooloose/syntastic"
hook_add = '''
  let g:syntastic_javascript_checkers = ['jsl']
  let g:syntastic_javascript_args = '-conf "c:/home/jsl.conf"'
  let g:syntastic_ruby_checkers = ['mri', 'rubocop']
'''

[[plugins]]
# 書いたスクリプトを即実行 ,r
repo = "thinca/vim-quickrun"
hook_add = '''
  " KEY MAP
  let g:quickrun_no_default_key_mappings = 1
  silent! map <unique> ,r <Plug>(quickrun)

  " config
  let g:quickrun_config = {
  \   '_': {
  \       'output/buffer/split': 'botright 8sp',
  \       'hook/time/enable': '1',
  \       'runner': 'vimproc',
  \       'outputter/buffer/close_on_empty': 1,
  \       'runner/vimproc/updatetime': 60,
  \   },
  \   'lua': {'command': 'luajit'},
  \}
'''

[[plugins]]
# QFixHowm 一人お手軽wikiもどき
repo = "fuenor/qfixhowm"
