[[plugins]]
# toml syntax
repo = "cespare/vim-toml"
on_ft = "toml"

[[plugins]]
# Golang
repo = "vim-jp/vim-go-extra"
on_ft = "golang"

# Ruby
[[plugins]]
repo = "vim-ruby/vim-ruby"
on_ft = "ruby"

[[plugins]]
repo = "ecomba/vim-ruby-refactoring"
on_ft = "ruby"
hook_source = '''
  " デフォルトのキーマップを有効にする
  let g:ruby_refactoring_map_keys=0
'''

[[plugins]]
# Gauche(scheme)
repo = "aharisu/vim-gdev"
on_ft = "scheme"

[[plugins]]
# 行単位のdiff
repo = "AndrewRadev/linediff.vim"
on_cmd = ["Linediff", "LinediffReset"]

[[plugins]]
repo = "Shougo/neomru.vim"

[[plugins]]
repo = "Shougo/tabpagebuffer.vim"

# unite.vim
[[plugins]]
repo = "Shougo/unite.vim"
depends = ["neomru.vim", "tabpagebuffer.vim"]
on_cmd = ["Unite", "UniteWithCurrentDir", "UniteWithBufferDir", "UniteWithInput", "UniteWithCursorWord", "UniteClose", "UniteBookmarkAdd"]
hook_add = '''
  source $HOME/.vim/rc/plugins/unite.keymap.vim
'''
hook_source = '''
  source $HOME/.vim/rc/plugins/unite.rc.vim
'''
[[plugins]]
repo = "Shougo/unite-outline"
hook_source = '''
  nnoremap <silent> ,uo :<C-u>Unite -buffer-name=outline outline<CR>
'''

# unite sources <<<<<<<<<<<<<<<<<<<<<<<<<
[[plugins]]
repo = "tsukkee/unite-tag"
hook_source = '''
  augroup UniteTagKeyMaping
    autocmd!
    autocmd BufEnter *
      \   if empty(&buftype)
      \|     noremap <silent> ,ut :<C-u>UniteWithCursorWord -immediately tag<CR>
      \|  endif
  augroup END
'''

[[plugins]]
repo = "ujihisa/unite-gem"
on_ft = "ruby"

[[plugins]]
repo = "ujihisa/unite-rake"
on_ft = "ruby"

[[plugins]]
repo = "rhysd/unite-ruby-require.vim"
on_ft = "ruby"
hook_source = '''
  nnoremap <silent> ,ui :<C-u>Unite -buffer-name=require ruby/require<CR>
'''

[[plugins]]
# howm 一人お手軽wikiもどき
repo = "osyo-manga/unite-qfixhowm"
on_source = "unite.vim"
hook_source = '''
  call unite#custom_source('qfixhowm', 'sorters',
       \ ['sorter_qfixhowm_updatetime', 'sorter_reverse'])
'''
hook_add = '''
  nnoremap <silent> ,uh  :<C-u>Unite -no-start-insert qfixhowm<CR>
'''
# unite sources >>>>>>>>>>>>>>>>>>>>>>>>>

[[plugins]]
repo = "Shougo/vimfiler.vim"
depends = ["unite.vim", "vimproc.vim", "tabpagebuffer.vim"]
on_cmd = ["VimFiler", "VimFilerBufferDir"]
hook_add = '''
  source $HOME/.vim/rc/plugins/vimfiler.keymap.vim
'''
hook_source = '''
  source $HOME/.vim/rc/plugins/vimfiler.rc.vim
'''

[[plugins]]
repo = "Shougo/vimshell.vim"
depends = ["unite.vim", "vimproc.vim", "tabpagebuffer.vim"]
on_cmd = ["VimShell", "VimShellCreate", "VimShellTab", "VimShellPop", "VimShellCurrentDir", "VimShellBufferDir", "VimShellExecute", "VimShellInteractive", "VimShellTerminal", "VimShellSendString", "VimShellSendBuffer"]
hook_add = '''
  source $HOME/.vim/rc/plugins/vimshell.keymap.vim
'''
hook_source = '''
  source $HOME/.vim/rc/plugins/vimshell.rc.vim
'''

[[plugins]]
# NeoComplate ポップアップ補完
repo = "Shougo/neocomplete.vim"
on_i = 1
hook_source = '''
  source $HOME/.vim/rc/plugins/neocomplete.rc.vim
'''

[[plugins]]
# NeoSnippet.vim スニペットのポップアップ補完
repo = "Shougo/neosnippet.vim"
depends = ["neosnippet-snippets"]
on_i = 1
hook_source = '''
  source $HOME/.vim/rc/plugins/neosnippet.rc.vim
'''

[[plugins]]
# neosnip.vim の default snippets
repo = "Shougo/neosnippet-snippets"
on_source = "neosnippet.vim"

[[plugins]]
# その他 snippets
repo = "honza/vim-snippets"
on_source = "neosnippet.vim"

[[plugins]]
# 個人用 snippets
repo = "mugyu/vim-user-snippets"
on_source = "neosnippet.vim"

[[plugins]]
# Vimdoc-ja 日本語ヘルプ
repo = "vim-jp/vimdoc-ja"
on_cmd = "help"
