[[plugins]]
# 非同期で外部コマンドを実行したりとか
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
# colorscheme
repo = "tomasr/molokai"

[[plugins]]
# text-object の縁側版
repo = "tpope/vim-surround"
hook_add = '''
  augroup VimSurroundFileTypeSetting
    " ruby
    autocmd!
    autocmd FileType ruby let b:surround_{char2nr("i")} = "if \1condition: \1 \r end"
    autocmd FileType ruby let b:surround_{char2nr("d")} = "def \1method: \1 \r end"
    " erb
    autocmd FileType eruby let b:surround_{char2nr("-")} = "<% \r %>"
    autocmd FileType eruby let b:surround_{char2nr("%")} = "<% \r %>"
    autocmd FileType eruby let b:surround_{char2nr("=")} = "<%= \r %>"
    " php
    autocmd FileType php let b:surround_{char2nr("-")} = "<? \r ?>"
    autocmd FileType php let b:surround_{char2nr("?")} = "<? \r ?>"
    autocmd FileType php let b:surround_{char2nr("=")} = "<?= \r ?>"
    autocmd FileType php let b:surround_{char2nr("a")} = "array(\r)"
    " javascript
    autocmd FileType javascript let b:surround_{char2nr("f")} = "function \1function:\1() {\r}"
    autocmd FileType javascript let b:surround_{char2nr("F")} = "function() {\r}"
  augroup END
'''

[[plugins]]
# vim-surrond とかの操作をリピートできる
repo = "tpope/vim-repeat"

[[plugins]]
# テキスト整形用
repo = "h1mesuke/vim-alignta"

[[plugins]]
# レジスタの履歴を取得・再利用する<c-p>, <c-n>
repo = "LeafCage/yankround.vim"
hook_add = '''
  " keymap
  nmap p <Plug>(yankround-p)
  xmap p <Plug>(yankround-p)
  nmap P <Plug>(yankround-P)
  nmap gp <Plug>(yankround-gp)
  xmap gp <Plug>(yankround-gp)
  nmap gP <Plug>(yankround-gP)
  nmap <C-p> <Plug>(yankround-prev)
  nmap <C-n> <Plug>(yankround-next)

  " yankound history with unite.vim
  nnoremap <silent> ,ur :<C-u>Unite -buffer-name=yankound yankround<CR>

  " highlight
  let g:yankround_use_region_hl=1

  " cache directory
  let g:yankround_dir="~/.cache/yankround"
'''

[[plugins]]
# カレンダー
repo = "vim-scripts/calendar.vim"

[[plugins]]
# nishigori/increment-activator
repo = "nishigori/increment-activator"
hook_add = '''
  let g:increment_activator_filetype_candidates =
  \ {
  \   '_': [
  \     [
  \       'zero', 'one', 'two', 'three', 'four', 'five',
  \       'six',  'seven', 'eight', 'nine', 'ten',
  \       'eleven', 'twelve', 'thirteen', 'fourteen', 'fifteen',
  \       'sixteen', 'seventeen', 'eighteen', 'nineteen', 'twenty'
  \     ],
  \     [
  \       '1st', '2nd', '3rd', '4th', '5th',
  \       '6th', '7th', '8th', '9th', '10th',
  \       '11th', '12th', '13th', '14th', '15th',
  \       '16th', '17th', '18th', '19th', '20th',
  \     ],
  \     [
  \       'first', 'second', 'third', 'fourth', 'fifth',
  \       'sixth', 'seventh', 'eighth', 'ninth', 'tenth',
  \       'eleventh', 'twelfth', 'thirteenth', 'fourteenth', 'fifteenth',
  \       'sixteenth', 'seventeenth', 'eighteenth', 'nineteenth', 'twentieth',
  \     ],
  \     ['i', 'ii', 'iii', 'iv', 'v', 'vi', 'vii', 'viii', 'ix', 'x'],
  \     ['foo', 'bar', 'baz', 'qux', 'quux', 'hoge', 'piyo', 'fuga', 'hogera'],
  \     ['left', 'right'],
  \     ['top', 'bottom'],
  \     ['noth', 'east', 'south', 'west'],
  \     ['under', 'over'],
  \     ['start', 'stop'],
  \     ['begin', 'end'],
  \     ['next', 'previous'],
  \     ['read', 'write'],
  \     ['draw', 'erase'],
  \     ['old', 'new'],
  \     ['first', 'second', 'th'],
  \     ['min', 'max'],
  \     ['head', 'body', 'tail'],
  \     ['lose', 'find'],
  \     ['in', 'out'],
  \     ['input', 'output'],
  \     ['export', 'inport'],
  \     ['parent', 'child', 'children'],
  \     ['push', 'pull', 'pop'],
  \     ['good', 'bad'],
  \     ['same', 'different'],
  \     ['create', 'destory'],
  \     ['prefix', 'sufix'],
  \     ['some', 'any', 'every', 'no'],
  \   ],
  \   'ruby': [
  \     ['if', 'unless'],
  \   ],
  \   'php': [
  \     ['extends', 'implements'],
  \     ['require', 'require_once', 'imclude', 'include_once'],
  \   ]
  \ }
'''

[[plugins]]
# [, (, {, ", ' に対して閉じカッコを補完
repo = "kana/vim-smartinput"
hook_add = '''
  call smartinput#map_to_trigger('i', '<Plug>(smartinput_BS)',
        \                        '<BS>',
        \                        '<BS>')
  call smartinput#map_to_trigger('i', '<Plug>(smartinput_C-h)',
        \                        '<BS>',
        \                        '<C-h>')
  call smartinput#map_to_trigger('i', '<Plug>(smartinput_CR)',
        \                        '<Enter>',
        \                        '<Enter>')
'''

[[plugins]]
# do などに対して end を補完
repo = "cohama/vim-smartinput-endwise"
depends = 'vim-smartinput'
hook_add = '''
  call smartinput_endwise#define_default_rules()
'''

[[plugins]]
# vim の正規表現を Perl や Ruby っぽくする
repo = "othree/eregex.vim"

[[plugins]]
# シンタックスチェックや臭いコードを調べる
repo = "scrooloose/syntastic"
hook_add = '''
  let g:syntastic_javascript_checkers = ['jsl']
  let g:syntastic_javascript_args = '-conf "c:/home/jsl.conf"'
  let g:syntastic_ruby_checkers = ['mri', 'rubocop']
'''

[[plugins]]
# 書いたスクリプトを即実行 ,r
repo = "thinca/vim-quickrun"
hook_add = '''
  " KEY MAP
  let g:quickrun_no_default_key_mappings = 1
  silent! map <unique> ,r <Plug>(quickrun)

  " config
  let g:quickrun_config = {
  \   '_': {
  \       'output/buffer/split': 'botright 8sp',
  \       'hook/time/enable': '1',
  \       'runner': 'vimproc',
  \       'outputter/buffer/close_on_empty': 1,
  \       'runner/vimproc/updatetime': 60,
  \   },
  \   'lua': {'command': 'luajit'},
  \}
'''

[[plugins]]
# QFixHowm 一人お手軽wikiもどき
repo = "fuenor/qfixhowm"
