[[plugins]]
# 非同期で外部コマンドを実行したりとか
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
# colorscheme
repo = "tomasr/molokai"

[[plugins]]
# text-object の縁側版
repo = "tpope/vim-surround"
hook_add = '''
  source $HOME/.vim/rc/plugins/vim-surround.rc.vim
'''

[[plugins]]
# vim-surrond とかの操作をリピートできる
repo = "tpope/vim-repeat"

[[plugins]]
# テキスト整形用
repo = "h1mesuke/vim-alignta"

[[plugins]]
# レジスタの履歴を取得・再利用する<c-p>, <c-n>
repo = "LeafCage/yankround.vim"
hook_add = '''
  source $HOME/.vim/rc/plugins/yankround.rc.vim
'''

[[plugins]]
# カレンダー
repo = "vim-scripts/calendar.vim"

[[plugins]]
# nishigori/increment-activator
repo = "nishigori/increment-activator"
hook_add = '''
  source $HOME/.vim/rc/plugins/increment-activator.rc.vim
'''

[[plugins]]
# [, (, {, ", ' に対して閉じカッコを補完
repo = "kana/vim-smartinput"
hook_add = '''
  source $HOME/.vim/rc/plugins/vim-smartinput.rc.vim
'''

[[plugins]]
# do などに対して end を補完
repo = "cohama/vim-smartinput-endwise"
depends = 'vim-smartinput'
hook_add = '''
  call smartinput_endwise#define_default_rules()
'''

[[plugins]]
# vim の正規表現を Perl や Ruby っぽくする
repo = "othree/eregex.vim"

[[plugins]]
# シンタックスチェックや臭いコードを調べる
repo = "scrooloose/syntastic"
hook_add = '''
  source $HOME/.vim/rc/plugins/syntastic.rc.vim
'''

[[plugins]]
# 書いたスクリプトを即実行 ,r
repo = "thinca/vim-quickrun"
hook_add = '''
  source $HOME/.vim/rc/plugins/vim-quickrun.rc.vim
'''

[[plugins]]
# QFixHowm 一人お手軽wikiもどき
repo = "fuenor/qfixhowm"
hook_add = '''
  source $HOME/.vim/rc/plugins/qfixhowm.rc.vim
'''
